spring:
  application:
    name: product-service
server:
  port: 8071

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/
logging:
  level:
    com.example.product.service.UserService: debug
ribbon:
  ReadTimeout: 1000
  ConnectTimeout: 1000
